### ISSUE TITLE
crash when attacking health potion

### ISSUE THREAD

**Issue by FpsLex** [Surnichka/2DPlatfomer#1]
Game crashes after the player attacks the health potion that spawns upon the death of an enemy while it's still in the air. The game doesn't crash if you pick up the potion while it's in the air without attacking or if the potion is already on the ground.

**Comment by FpsLex** [comment]
https://i.imgur.com/LuVabwG.png

**Comment by Surnichka** [comment]
It has been fixed in the last commit
